### ISSUE TITLE
Campo stack?

### ISSUE THREAD

**Issue by gabrielperales** [MurciaDev/murcia-tech-hub#3]
Deberíamos añadir un campo stack? 🤔  

Creo que esto puede ser útil a la hora de buscar trabajo, saber si X empresa utiliza Y.

**Comment by dvigueras** [comment]
A mí me parece útil.

**Comment by klaufel** [comment]
+1, y puede ser interesante también los perfiles que tienen de forma interna las empresas o que contratan también a nivel externo. 

Frontend (React, Next.js, ...)
Backend (Kotlin, Java, ...) 
UX/UI (Figma, Sketch, ...)
Data insight  (Analytics, Adobe, ...)

Toda información que sepamos de la empresa nutrirá el listado. Me parece interesante, pero quizás se queda demasiado extenso y un poco "escueto" con algunas y algo poco mantenible, aquí debería de ser las propias empresas o propios perfiles que estén en esas empresas que puedan estar en la comunidad las que actualicen la información.

¿Qué os parece?
